---

- name: Get latest Atom rpm URL
  uri:
    url: https://atom.io/download/rpm
    body_format: json
    return_content: no
  register: atom_latest_rpm

- name: Install Atom rpm
  become: yes
  dnf:
    name: "{{ atom_latest_rpm.url }}"
    state: present

- name: Create array with users
  shell: "cut -d: -f1 /etc/passwd"
  register: system_users
  changed_when: false # This will never report 'changed' status. But it will report 'ok', 'unreachable' or 'failed'

- name: Create Nemo action directory
  become: yes
  become_user: "{{ item.name }}"
  file:
    path: "{{ item.home }}/.local/share/nemo/actions"
    state: directory
    mode: 0755
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  when: item.name in system_users.stdout_lines and atom_add_action
  with_items: "{{ atom_users }}"

- name: Add action "Open with Atom" to Nemo
  become: yes
  become_user: "{{ item.name }}"
  copy:
    src: "{{ atom_action_template }}"
    dest: "{{ item.home }}/.local/share/nemo/actions/atom.nemo_action"
    mode: 0664
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  when: item.name in system_users.stdout_lines and atom_add_action
  with_items: "{{ atom_users }}"

- name: Link Atom configuration with portable directory
  become: yes
  become_user: "{{ item.name }}"
  file:
    src: "{{ item.conf }}"
    dest: "{{ item.home }}/.atom"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    state: link
  when: item.name in system_users.stdout_lines and item.conf != ''
  with_items: "{{ atom_users }}"
